apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-secret-template
  title: Create Secret - Self-Service Flow
  description: Flow to enable external resources into your k8s cluster to be used by TIBCO workloads
  tags:
    - import-flow
    - tibco
    - bwce
    - recommended
spec:
  owner: tibco-templates
  type: bwce

  parameters:
    - title: Basic Information
      required:
        - secretName
        - namespace
        - content
      properties:
        secretName:
          title: Secret Name
          type: string
          description: Name of the secret will be created
        namespace:
          title: Namespace Name
          type: string
          description: Name of the namespace where the secret will be created
        content:
          type: string
          format: data-url
          title: File to upload

  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch
      name: Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values: {}
    - id: shell
      name: shell
      action: custom:command:execute
      input:
        scriptPath: ./post-script.sh
        arguments: [ "${{ parameters.secretName }}" , "${{ parameters.namespace }}" , "${{ parameters.content }}" ]
    - id: wait
      name: wait
      action: debug:wait
      input:
        minutes: 1
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
