apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  links:
    - title: VSCode Editor (File)
      url: vscode://file/${{ values.localFolder }}/call-service.flogo
    - title: VSCode Editor (Folder)
      url: vscode://file/${{ values.localFolder }}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
  providesApis: ['${{values.name}}-api']
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ${{values.name}}-api-location
spec:
  targets:
    - ./catalog-api.yaml
